openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8000
    description: Generated server url
paths:
  /{w}:
    get:
      tags:
        - word-controller
      operationId: getWord
      parameters:
        - name: w
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Definition'
  /:
    get:
      tags:
        - word-controller
      operationId: getAllWords
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Definition'
components:
  schemas:
    Definition:
      type: object
      properties:
        word:
          type: string
        definition:
          type: string
        id:
          type: integer
          format: int32
